#!/bin/bash

set -e

cafile="/var/lib/ca-certificates/java-cacerts"
cafile_gcj="/var/lib/ca-certificates/gcj-cacerts"
cadir="/var/lib/ca-certificates/pem"


for i in "$@"; do
	if [ "$i" = "-f" ]; then
		fresh=1
	elif [ "$i" = "-v" ]; then
		verbose=1
	fi
done

[ -z "$verbose" ] || echo "creating $cafile ..."
trust extract --format=java-cacerts --purpose=server-auth --filter=ca-anchors --overwrite $cafile

# vim: syntax=sh
