#!/usr/bin/perl -w
#
# update-ca-certificates
#
# Copyright (c) 2010,2013 SUSE Linux Products GmbH
# Author: Ludwig Nussel
#
# Inspired by Debian's update-ca-certificates
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301,
# USA.
#

use strict;

use File::Basename;
use Getopt::Long;

my $hooksdir1 = '/etc/ca-certificates/update.d';
my $hooksdir2 = '/usr/lib/ca-certificates/update.d';

my %options;

Getopt::Long::Configure("no_ignore_case");
GetOptions(
	\%options,
	"verbose|v",
	"fresh|f",
	"help|h",
    ) or die "$!\n";

if ($options{help})
{
	print "USAGE: $0 [OPTIONS]\n";
	print "OPTIIONS:\n";
	print "  --verbose, -v     verbose output\n";
	print "  --fresh, -f       start from scratch\n";
	print "  --help, -h        this screen\n";
	exit 0;
}

# set sane umask
umask 0222;

my @args;
push @args, '-f' if $options{fresh};
push @args, '-v' if $options{verbose};
for my $f (sort(glob("$hooksdir2/*.run"), glob("$hooksdir1/*.run"))) {
	print "running $f ...\n" if $options{verbose};
	system($f, @args);
}
