---
name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  tests:
    name: Test containers
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v6
      - name: set up Python
        uses: actions/setup-python@v6
      - name: install dependencies
        run: pip install --user pytest-xdist testinfra
      - name: run tests
        run: pytest -vv -n $(nproc)
